# docker-compose.yml
version: '3.0'
services:
  rasa:
    build:
      context: .
      dockerfile: Dockerfile.rasa
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    command: run --enable-api --cors "*"

  action_server:
    build:
      context: .
      dockerfile: Dockerfile.actions
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions